### PR TITLE
Validate version of the VoteState struct before doing anything

### PR DESCRIPTION
**Pull request by im-0**
(WARNING: untested!)

It looks like current Solana implementation supports multiple versions of the VoteState structure[1]. I am not sure whether old format vote accounts may still exist or not, but it will be better to check version just in a case if another new vote state version will appear in future versions of Solana.

[1] https://github.com/solana-labs/solana/blob/656b150e575a4d16cfa9c9ff63b16edcf94f2e0d/sdk/program/src/vote/state/vote_state_versions.rs#L4

### CODE REVIEW

**Comment by im-0** [comment]
Patchset V2:
- Allow SetLeaveEpoch and Leave with any version of VoteState struct.

**Comment by bji** [comment]
As discussed in Discord, I think this change is not needed.  Leave is already possible regardless of Vote Account state version, since the vote account state is not read in Leave.

It is extremely unlikely that the vote account state will ever be changed to a version that moves the commission field; but in the unlikely event that this happens, the following effects would be observed:

a) When a validator Enters the program, it may be incorrectly accepted or rejected.  In the case of an incorrect rejection, this really isn't a problem -- a new version of the program should be available for the use of the validator anyway.  In the case of an incorrect acceptance, it will be possible for stakers to identify that the validator has set a lower max commission and can de-stake if desired.

b) If a validator has a max commission increase rate set, then they may be incorrectly allowed to or disallowed from increasing commission if the Vote State format changes and the incorrect commission is read from it.  In both cases, the validator can still Leave the program to move to a new version that is aware of the newer Vote State format.  The effect of being allowed to increase commission more than configured, again stakers will be able to detect this and can de-stake from the untrustworthy validator who is changing commission using a loophole.

Neither (a) nor (b) are a serious issue.

The only possible implementation change is to:

1. Check for Vote State of a vote account beyond the known version on Enter, and reject Enter if the Vote Account state version is larger than known values.

2. Check for Vote State of a vote account at the time of commission change, and reject the commission change if the Vote State version is newer than known.

(1) can be accomplished by checking the Vote State of the vote account before issuing the Enter transaction in the vamp program; this will still allow someone using self-authored transactions to Enter the program even if the Vote Account state is of too new a version, but it's not expected that many validators would choose to do this.  This will be implemented but won't require a change to the on-chain program.

(2) can only be accomplished in a newly published version of the program (at a new program account address).

I am still considering whether to do these things in a new version of the program ... they are such minor issues and until the VoteState version actually changes in a non-backwards compatible way (highly, highly, HIGHLY unlikely) these aren't even issues of any consequence anyway.

**Comment by bji** [comment]
I've addressed the issue of Enter when Vote Account state version is too large in commit d63a2df.

I've added some code comments to describe the potential hazards of Vote Account state version changing in commit 7d6a826.

I believe that the likelihood of a change to the Vote State that would invalidate the commission fetching code is so unlikely, and the consequences so insignificant, as to not require any further changes at this time.

**Comment by bji** [comment]
Thanks for the pull request but I believe the comments and changes I've made already cover this issue.

**Pull request closed without merging**
